name: btc_simulation
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_fonts: ^6.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.12.0
  intl: ^0.20.2
  animated_flip_counter: ^0.3.4
  lottie: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1


flutter:


  uses-material-design: true

  assets:
     - assets/images/
